spring:
  jackson: 
     time-zone: "GMT+8"
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource: 
    url: jdbc:mysql:///goodsmanage?characterEncoding=utf-8
    username: root
    password: usbw
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8